<a href="https://colab.research.google.com/github/jenswilly/ml-keras/blob/master/colab-keras-text-gen.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np
values = np.array( [[20,18,17,10],[18,21,21,23],[17,32,19,20]] )
values = values.astype( 'float32' ) # Convert all to float32
print( values )
values -= np.mean( values )
print( f"New mean: {np.mean(values)}") # Almost zero (6e-07)?
values /= np.std( values )
print( f"New std. dev.: {np.std(values)}")


[[20. 18. 17. 10.]
 [18. 21. 21. 23.]
 [17. 32. 19. 20.]]
New mean: 6.35782896551973e-07
New std. dev.: 1.0


In [19]:
np.argmax(values, axis=0)

array([0, 2, 1, 1])

In [18]:
values

array([[ 0.06892469, -0.34462264, -0.5513963 , -1.998812  ],
       [-0.34462264,  0.27569833,  0.27569833,  0.68924564],
       [-0.5513963 ,  2.5502086 , -0.13784897,  0.06892469]],
      dtype=float32)